LifeSureApp/Controllers/AboutController.cs
using LifeSureApp.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSureApp.Controllers
{
    public class AboutController : Controller
    {
        DayNightDbEntities db = new DayNightDbEntities();
        public ActionResult AboutList()
        {
            var values = db.Tbl_About.ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult UpdateAbout(int id)
        {
            var value = db.Tbl_About.Find(id);
            return View(value);
        }
        [HttpPost]
        public ActionResult UpdateAbout(Tbl_About About)
        {
            var value = db.Tbl_About.Find(About.AboutId);

            value.AboutTitle = About.AboutTitle;
            value.AboutMinDescription = About.AboutMinDescription;
            value.AboutImageURL = About.AboutImageURL;
            db.SaveChanges();
            return RedirectToAction("AboutList");
        }
    }
}

LifeSureApp/Controllers/ContactController.cs
using LifeSureApp.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSureApp.Controllers
{
    public class ContactController : Controller
    {
        DayNightDbEntities db = new DayNightDbEntities();
        public ActionResult ContactList()
        {
            var contacts = db.Tbl_Contact.ToList();
            return View(contacts);
        }

        [HttpGet]
        public ActionResult AddContact()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddContact(Tbl_Contact contact)
        {
            db.Tbl_Contact.Add(contact);
            db.SaveChanges();
            return RedirectToAction("Contact");
        }

        public ActionResult DeleteContact(int id)
        {
            var contact = db.Tbl_Contact.Find(id);
            db.Tbl_Contact.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Contact");
        }

        [HttpGet]
        public ActionResult UpdateContact(int id)
        {
            var contact = db.Tbl_Contact.Find(id);
            return View(contact);
        }

        [HttpPost]
        public ActionResult UpdateContact(Tbl_Contact contact)
        {
            var existingContact = db.Tbl_Contact.Find(contact.ContactId);
            existingContact.ContactAddress = contact.ContactAddress;
            existingContact.ContactEmail = contact.ContactEmail;
            existingContact.ContactPhone = contact.ContactPhone;
            db.SaveChanges();
            return RedirectToAction("Contact");
        }
    }
}

LifeSureApp/Controllers/EmployeeController.cs
using LifeSureApp.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSureApp.Controllers
{
    public class EmployeeController : Controller
    {
        DayNightDbEntities db = new DayNightDbEntities();
        public ActionResult EmployeeList()
        {
            var employees = db.Tbl_Employee.ToList();
            return View(employees);
        }

        [HttpGet]
        public ActionResult AddEmployee()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddEmployee(Tbl_Employee employee)
        {
            db.Tbl_Employee.Add(employee);
            db.SaveChanges();
            return RedirectToAction("EmployeeList");
        }

        public ActionResult DeleteEmployee(int id)
        {
            var employee = db.Tbl_Employee.Find(id);
            db.Tbl_Employee.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("EmployeeList");
        }

        [HttpGet]
        public ActionResult UpdateEmployee(int id)
        {
            var employee = db.Tbl_Employee.Find(id);
            return View(employee);
        }

        [HttpPost]
        public ActionResult UpdateEmployee(Tbl_Employee employee)
        {
            var existingEmployee = db.Tbl_Employee.Find(employee.EmployeeId);
            existingEmployee.EmployeeFullName = employee.EmployeeFullName;
            existingEmployee.EmployeeTitle = employee.EmployeeTitle;
            existingEmployee.EmployeePhotoURL = employee.EmployeePhotoURL;
            existingEmployee.EmployeeFacebook = employee.EmployeeFacebook;
            existingEmployee.EmployeeX = employee.EmployeeX;
            existingEmployee.EmployeeLinkedin = employee.EmployeeLinkedin;
            existingEmployee.EmployeeInstagram = employee.EmployeeInstagram;
            db.SaveChanges();
            return RedirectToAction("EmployeeList");
        }
    }
}

LifeSureApp/Controllers/FeatureController.cs
using LifeSureApp.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSureApp.Controllers
{
    public class FeatureController : Controller
    {
       DayNightDbEntities db= new DayNightDbEntities();
        public ActionResult FeatureList()
        {
            var features = db.Tbl_Feature.ToList();
            return View(features);
        }

        [HttpGet]
        public ActionResult AddFeature()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddFeature(Tbl_Feature feature)
        {
            db.Tbl_Feature.Add(feature);
            db.SaveChanges();
            return RedirectToAction("FeatureList");
        }

        public ActionResult DeleteFeature(int id)
        {
            var feature = db.Tbl_Feature.Find(id);
            db.Tbl_Feature.Remove(feature);
            db.SaveChanges();
            return RedirectToAction("FeatureList");
        }


    }
}

LifeSureApp/Controllers/HomeController.cs
using LifeSureApp.Models.DataModels;
using LifeSureApp.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace LifeSureApp.Controllers
{
    public class HomeController : Controller
    {
        DayNightDbEntities db = new DayNightDbEntities();

        public async Task<ActionResult> Index()
        {

            var linkedInService = new LinkedinServices();
            var linkedInUser = await linkedInService.GetUserInfo("muratyucedag");

            return View(linkedInUser);
        }

        public PartialViewResult Feature()
        {
            var features = db.Tbl_Feature.ToList();
            return PartialView(features);
        }

        public PartialViewResult SubFeature()
        {
            var values = db.Tbl_SubFeature
                .OrderByDescending(x => x.SubFeatureId)
                .Take(4)
                .ToList();
            return PartialView(values);
        }

        public PartialViewResult About()
        {
            var about = db.Tbl_About.ToList();
            return PartialView(about);
        }


        public PartialViewResult Service()
        {
            var values = db.Tbl_Service
                .OrderByDescending(x => x.ServiceId) 
                .Take(4)
                .ToList();
            return PartialView(values);
        }
        public PartialViewResult Employee()
        {
            var employees = db.Tbl_Employee.ToList();
            return PartialView(employees);
        }

        public PartialViewResult Testimonial()
        {
            var testimonials = db.Tbl_Testimonial.ToList();
            return PartialView(testimonials);
        }
        public PartialViewResult Contact()
        {
            var contacts = db.Tbl_Contact.ToList();
            return PartialView(contacts);
        }
        public PartialViewResult Spinner()
        {
            return PartialView();
        }
        public PartialViewResult Navbar()
        {
            return PartialView();
        }
        public PartialViewResult Scripts()
        {
            return PartialView();
        }

        public PartialViewResult FAQ()
        {
            var faq = db.Tbl_Question.OrderByDescending(x => x.QuestionId)
                .Take(4)
                .ToList();
            return PartialView(faq);
        }
    }
}

LifeSureApp/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace LifeSureApp.Controllers
{
    public class LanguageController : Controller
    {
        // GET: Language
        public ActionResult Change(string lang, string returnUrl)
        {
            if (!string.IsNullOrEmpty(lang))
            {
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(lang);
                Thread.CurrentThread.CurrentCulture = new CultureInfo(lang);

                HttpCookie cookie = new HttpCookie("lang", lang);
                cookie.Expires = DateTime.Now.AddYears(1);
                Response.Cookies.Add(cookie);
            }
            return Redirect(returnUrl ?? "/");

        }
    }
}

LifeSureApp/Controllers/SubFeatureController.cs
using LifeSureApp.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSureApp.Controllers
{
    public class SubFeatureController : Controller
    {
        DayNightDbEntities db = new DayNightDbEntities();
        public ActionResult SubFeatureList()
        {
            var SubFeatures = db.Tbl_SubFeature.ToList();
            return View(SubFeatures);
        }

        [HttpGet]
        public ActionResult AddSubFeature()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddSubFeature(Tbl_SubFeature SubFeature)
        {
            db.Tbl_SubFeature.Add(SubFeature);
            db.SaveChanges();
            return RedirectToAction("SubFeatureList");
        }

        public ActionResult DeleteSubFeature(int id)
        {
            var SubFeature = db.Tbl_SubFeature.Find(id);
            db.Tbl_SubFeature.Remove(SubFeature);
            db.SaveChanges();
            return RedirectToAction("SubFeatureList");
        }

        [HttpGet]
        public ActionResult UpdateSubFeature(int id)
        {
            var SubFeature = db.Tbl_SubFeature.Find(id);
            return View(SubFeature);
        }

        [HttpPost]
        public ActionResult UpdateSubFeature(Tbl_SubFeature SubFeature)
        {
            var existingSubFeature = db.Tbl_SubFeature.Find(SubFeature.SubFeatureId);
            existingSubFeature.SubFeatureTitle = SubFeature.SubFeatureTitle;
            existingSubFeature.SubFeatureDescription = SubFeature.SubFeatureDescription;
            existingSubFeature.SubFeatureIcon = SubFeature.SubFeatureIcon;
            db.SaveChanges();
            return RedirectToAction("SubFeatureList");
        }

    }
}

LifeSureApp/Controllers/TestimonialController.cs
using LifeSureApp.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LifeSureApp.Controllers
{
    public class TestimonialController : Controller
    {
        DayNightDbEntities db = new DayNightDbEntities();
        public ActionResult TestimonialList()
        {
            var testimonials = db.Tbl_Testimonial.ToList();
            return View(testimonials);
        }

        [HttpGet]
        public ActionResult AddTestimonial()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddTestimonial(Tbl_Testimonial testimonial)
        {
            db.Tbl_Testimonial.Add(testimonial);
            db.SaveChanges();
            return RedirectToAction("TestimonialList");
        }

        public ActionResult DeleteTestimonial(int id)
        {
            var testimonial = db.Tbl_Testimonial.Find(id);
            db.Tbl_Testimonial.Remove(testimonial);
            db.SaveChanges();
            return RedirectToAction("TestimonialList");
        }

        [HttpGet]
        public ActionResult UpdateTestimonial(int id)
        {
            var testimonial = db.Tbl_Testimonial.Find(id);
            return View(testimonial);
        }

        [HttpPost]
        public ActionResult UpdateTestimonial(Tbl_Testimonial testimonial)
        {
            var existingTestimonial = db.Tbl_Testimonial.Find(testimonial.TestimonialId);
            existingTestimonial.TestimonialFullName = testimonial.TestimonialFullName;
            existingTestimonial.TestimonialTitle = testimonial.TestimonialTitle;
            existingTestimonial.TestimonialDescription = testimonial.TestimonialDescription;
            existingTestimonial.TestimonialPhotoURL = testimonial.TestimonialPhotoURL;
            db.SaveChanges();
            return RedirectToAction("TestimonialList");
        }
    }
}

LifeSureApp/Views/Home/About.cshtml
@model List<LifeSureApp.Models.DataModels.Tbl_About>
<div class="container-fluid bg-light about pb-5">
    <div class="container pb-5">
        <div class="row g-5">
            <div class="col-xl-6 wow fadeInLeft" data-wow-delay="0.2s">
                <div class="about-item-content bg-white rounded p-5 h-100">
                    @foreach (var item in Model)
                    {


                        <h4 class="text-primary">Şirketimiz Hakkında</h4>
                        <h1 class="display-4 mb-4"></h1>
                        <p>
                            @item.AboutMinDescription
                        </p>


                    }
                </div>
            </div>
            <div class="col-xl-6 wow fadeInRight" data-wow-delay="0.2s">
                <div class="bg-white rounded p-5 h-100">
                    <div class="row g-4 justify-content-center">
                        <div class="col-12">
                            <div class="rounded bg-light">
                                <img src="@Model.FirstOrDefault().AboutImageURL" class="img-fluid rounded w-100" alt="">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="counter-item bg-light rounded p-3 h-100">
                                <div class="counter-counting">
                                    <span class="text-primary fs-2 fw-bold" data-toggle="counter-up">10</span>
                                    <span class="h1 fw-bold text-primary">+</span>
                                </div>
                                <h4 class="mb-0 text-dark">Sigorta Poliçemiz</h4>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="counter-item bg-light rounded p-3 h-100">
                                <div class="counter-counting">
                                    <span class="text-primary fs-2 fw-bold" data-toggle="counter-up">100</span>
                                    <span class="h1 fw-bold text-primary">+</span>
                                </div>
                                <h4 class="mb-0 text-dark">Kazandığımız Ödül</h4>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="counter-item bg-light rounded p-3 h-100">
                                <div class="counter-counting">
                                    <span class="text-primary fs-2 fw-bold" data-toggle="counter-up">50</span>
                                    <span class="h1 fw-bold text-primary">+</span>
                                </div>
                                <h4 class="mb-0 text-dark">Nitelikli Temsilcimiz</h4>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="counter-item bg-light rounded p-3 h-100">
                                <div class="counter-counting">
                                    <span class="text-primary fs-2 fw-bold" data-toggle="counter-up">200</span>
                                    <span class="h1 fw-bold text-primary">+</span>
                                </div>
                                <h4 class="mb-0 text-dark">Takım Üyemiz</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LifeSureApp/Views/Home/Employee.cshtml
@model List<LifeSureApp.Models.DataModels.Tbl_Employee>
<div class="container-fluid team pb-5">
    <div class="container pb-5">
        <div class="text-center mx-auto pb-5 wow fadeInUp" data-wow-delay="0.2s" style="max-width: 800px;">
            <h4 class="text-primary">Our Team</h4>
            <h1 class="display-4 mb-4">Ekibimizle Tanışın</h1>
            <p class="mb-0">
                Hizmetlerimizin arkasındaki özverili profesyonellerle tanışın. Deneyimli ekibimiz, size güvenilir rehberlik, esnek çözümler ve en önemli varlıklarınızı korumak için ihtiyaç duyduğunuz desteği sağlamak için yorulmadan çalışır.
            </p>
        </div>
        <div class="row g-4">
            @foreach (var item in Model)
            {
                <div class="col-md-6 col-lg-6 col-xl-3 wow fadeInUp" data-wow-delay="0.2s">



                    <div class="team-item">

                        <div class="team-img">
                            <img src="@item.EmployeePhotoURL" class="img-fluid rounded-top w-100" alt="">
                            <div class="team-icon">
                                <a class="btn btn-primary btn-sm-square rounded-pill mb-2" href="@item.EmployeeFacebook"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-pill mb-2" href="@item.EmployeeX"><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-pill mb-2" href="@item.EmployeeLinkedin"><i class="fab fa-linkedin-in"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-pill mb-0" href="@item.EmployeeInstagram"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-title p-4">
                            <h4 class="mb-0">@item.EmployeeFullName</h4>
                            <p class="mb-0">@item.EmployeeTitle</p>
                        </div>

                    </div>

                </div>
            }
        </div>
    </div>
</div>

LifeSureApp/Views/Home/FAQ.cshtml
@model List<LifeSureApp.Models.DataModels.Tbl_Question>

<div class="container-fluid faq-section bg-light py-5">
    <div class="container py-5">
        <div class="row g-5 align-items-center">
            <div class="col-xl-6 wow fadeInLeft" data-wow-delay="0.2s">
                <div class="h-100">
                    <div class="mb-5">
                        <h4 class="text-primary">SSS</h4>
                        <h1 class="display-4 mb-0">Sıkça Sorulan Sorular</h1>
                    </div>
                    <div class="accordion" id="accordionExample">
                        @for (int i = 0; i < Model.Count; i++)
                        {
                            var item = Model[i];
                            var headingId = $"heading{i}";
                            var collapseId = $"collapse{i}";
                            var isFirst = i == 0;
                            var showClass = isFirst ? "show" : "";
                            var collapsedClass = isFirst ? "" : "collapsed";
                            var ariaExpanded = isFirst.ToString().ToLower();
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="@headingId">
                                    <button class="accordion-button @collapsedClass border-0" type="button"
                                            data-bs-toggle="collapse"
                                            data-bs-target="#@collapseId"
                                            aria-expanded="@ariaExpanded"
                                            aria-controls="@collapseId">
                                        S: @item.Question
                                    </button>
                                </h2>
                                <div id="@collapseId" class="accordion-collapse collapse @showClass"
                                     aria-labelledby="@headingId"
                                     data-bs-parent="#accordionExample">
                                    <div class="accordion-body rounded">
                                        C: @item.QuestionAnswer
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="col-xl-6 wow fadeInRight" data-wow-delay="0.4s">
                <img src="@Url.Content("~/Content/LifeSure-1.0.0/img/business-support-faq-concept-vector-42550114.jpg")"
                     class="img-fluid w-100"
                     alt="SSS Görseli">
            </div>
        </div>
    </div>
</div>

LifeSureApp/Views/Home/Feature.cshtml
@model List<LifeSureApp.Models.DataModels.Tbl_Feature>

<div class="header-carousel owl-carousel">
    @foreach (var item in Model)
    {


        <div class="header-carousel-item bg-primary">
            <div class="carousel-caption">
                <div class="container">
                    <div class="row g-4 align-items-center">
                        <div class="col-lg-7 animated fadeInLeft">
                            <div class="text-sm-center text-md-start">
                                <h4 class="text-white text-uppercase fw-bold mb-4">@Resources.SharedResource.FeatureTitle</h4>
                                <h1 class="display-1 text-white mb-4">@item.FeatureTitle</h1>
                                <p class="mb-5 fs-5">
                                    @item.FeatureDescription
                                    @item.FeatureSubDescription
                                </p>
                                <div class="d-flex justify-content-center justify-content-md-start flex-shrink-0 mb-4">
                                    <a class="btn btn-light rounded-pill py-3 px-4 px-md-5 me-2" href="@item.VideoURL"><i class="fas fa-play-circle me-2"></i> @Resources.SharedResource.FeatureVideoButton</a>
                                    <a class="btn btn-dark rounded-pill py-3 px-4 px-md-5 ms-2" href="@item.FeatureLink">@Resources.SharedResource.FeatureSeeDetail</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-5 animated fadeInRight">
                            <div class="calrousel-img" style="object-fit: cover;">
                                <img src="@item.ImageURL" class="img-fluid w-100" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

</div>

LifeSureApp/Views/Home/Index.cshtml
@model LifeSureApp.ViewModels.LinkedinViewModel

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <title>LifeSure - Life Insurance Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght%400,9..40,100..1000;1,9..40,100..1000&family=Inter:slnt,wght%40-10..0,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link rel="stylesheet" href="~/Content/LifeSure-1.0.0/lib/animate/animate.min.css" />
    <link href="~/Content/LifeSure-1.0.0/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="~/Content/LifeSure-1.0.0/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/Content/LifeSure-1.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/Content/LifeSure-1.0.0/css/style.css" rel="stylesheet">



    <style>
        :root {
            --bs-primary: #1976D2;
            --bs-secondary: #64B5F6;
            --bs-accent: #00B8D4;
            --bs-success: #43A047;
            --bs-warning: #FFD600;
            --bs-danger: #E53935;
            --bs-bg-light: #F5F7FA;
            --bs-bg-dark: #102542;
            --bs-text-main: #102542;
            --bs-text-secondary: #455A64;
        }

        /* Ana renkler */
        .text-primary {
            color: var(--bs-primary) !important;
        }

        .bg-primary {
            background-color: var(--bs-primary) !important;
        }

        .btn-primary {
            background-color: var(--bs-primary) !important;
            border-color: var(--bs-primary) !important;
            color: #fff !important;
        }

            .btn-primary:hover, .btn-primary:focus {
                background-color: var(--bs-secondary) !important;
                border-color: var(--bs-secondary) !important;
                color: #fff !important;
            }

        /* İkincil renk */
        .text-secondary {
            color: var(--bs-secondary) !important;
        }

        .bg-secondary {
            background-color: var(--bs-secondary) !important;
        }

        .btn-secondary {
            background-color: var(--bs-secondary) !important;
            border-color: var(--bs-secondary) !important;
            color: #fff !important;
        }

            .btn-secondary:hover, .btn-secondary:focus {
                background-color: var(--bs-primary) !important;
                border-color: var(--bs-primary) !important;
                color: #fff !important;
            }

        /* Vurgu */
        .text-accent {
            color: var(--bs-accent) !important;
        }

        .bg-accent {
            background-color: var(--bs-accent) !important;
        }

        /* Başarı, uyarı, hata */
        .text-success {
            color: var(--bs-success) !important;
        }

        .bg-success {
            background-color: var(--bs-success) !important;
        }

        .text-warning {
            color: var(--bs-warning) !important;
        }

        .bg-warning {
            background-color: var(--bs-warning) !important;
        }

        .text-danger {
            color: var(--bs-danger) !important;
        }

        .bg-danger {
            background-color: var(--bs-danger) !important;
        }

        /* Arka planlar */
        .bg-light {
            background-color: var(--bs-bg-light) !important;
        }

        .bg-dark, footer, .footer {
            background-color: var(--bs-bg-dark) !important;
            color: #fff !important;
        }

        /* Metin */
        .text-main {
            color: var(--bs-text-main) !important;
        }

        .text-secondary-main {
            color: var(--bs-text-secondary) !important;
        }

        /* Kart ve kutular için gölge ve geçiş */
        .card, .service-item, .accordion-item {
            box-shadow: 0 4px 24px 0 rgba(25,118,210,0.08), 0 1.5px 4px 0 rgba(100,181,246,0.08);
            border-radius: 1rem;
            transition: box-shadow 0.2s;
        }

            .card:hover, .service-item:hover, .accordion-item:hover {
                box-shadow: 0 8px 32px 0 rgba(25,118,210,0.16), 0 3px 8px 0 rgba(100,181,246,0.16);
            }

        /* Linkler */
        a {
            color: var(--bs-primary);
        }

            a:hover, a:focus {
                color: var(--bs-accent);
            }
    </style>



</head>




<body>

    @Html.Action("Spinner")
    <div class="container-fluid topbar px-0 px-lg-4 bg-light py-2 d-none d-lg-block">
        <div class="container">
            <div class="row gx-0 align-items-center">
                <div class="col-lg-8 text-center text-lg-start mb-lg-0">
                </div>
                <div class="col-lg-4 text-center text-lg-end">
                    <div class="d-flex justify-content-end">
                        <div class="d-flex border-end border-primary pe-3">

                            <a class="btn p-0 text-primary me-0" href="#"><i class="fab fa-linkedin-in"> ( @Model.FollowersCount ) </i></a>
                        </div>
                        <div class="dropdown ms-3">
                            <a href="#" class="dropdown-toggle text-dark" data-bs-toggle="dropdown">
                                <small>
                                    <i class="fas fa-globe-europe text-primary me-2"></i>
                                    @(System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName == "tr" ? Resources.SharedResource.Turkish : Resources.SharedResource.English)
                                </small>
                            </a>
                            <div class="dropdown-menu rounded">
                                <a href="@Url.Action("Change", "Language", new { lang = "en", returnUrl = Request.RawUrl })" class="dropdown-item">@Resources.SharedResource.English</a>
                                <a href="@Url.Action("Change", "Language", new { lang = "tr", returnUrl = Request.RawUrl })" class="dropdown-item">@Resources.SharedResource.Turkish</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Html.Action("Navbar")
    @Html.Action("Feature");
    @Html.Action("SubFeature");
    @Html.Action("About");
    @Html.Action("Service");
    @Html.Action("FAQ");
    @Html.Action("Employee");
    @Html.Action("Testimonial");
    @Html.Action("Contact");
    @Html.Action("Scripts");
</body>
</html>

LifeSureApp/Views/Home/Scripts.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/Content/LifeSure-1.0.0/lib/wow/wow.min.js"></script>
<script src="~/Content/LifeSure-1.0.0/lib/easing/easing.min.js"></script>
<script src="~/Content/LifeSure-1.0.0/lib/waypoints/waypoints.min.js"></script>
<script src="~/Content/LifeSure-1.0.0/lib/counterup/counterup.min.js"></script>
<script src="~/Content/LifeSure-1.0.0/lib/lightbox/js/lightbox.min.js"></script>
<script src="~/Content/LifeSure-1.0.0/lib/owlcarousel/owl.carousel.min.js"></script>
<script src="~/Content/LifeSure-1.0.0/js/main.js"></script>

LifeSureApp/Views/Home/Spinner.cshtml
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>